<!DOCTYPE html>
<html>

<body>
  <h1>Handling Failure With Catch</h1>
  <p>Your solutions for problems 1 and 2 will print in the console. Problem 3 will render to the HTML below.</p>

  <p id="error" style="color:red;"></p>
  <script>
    /*
    PROBLEM 1:
    The function evenOrOdd below takes a number (E.G. 7) and returns a promise which fulfills a string if the number is even, and rejects a different string if the number is odd.
    Invoke the function, passing it number 7. Handle success by logging out the fulfilled value. Handle failure by logging out the rejected value. Try different nunbers.
    */
    function evenOrOdd(num) { // rejects if num not even
      // Do not worry about how this function works internally
      return num % 2 === 0 ? Promise.resolve(`${num} is even!`) : Promise.reject(`${num} is odd.`)
    }
    // ENTER YOUR CODE HERE
    evenOrOdd(8).then(result =>{
      console.log(result);
    })
    .catch(result=>{
      console.log(result);
    })

    /*
    PROBLEM 2:
    The function fetchData below returns a promise which sometimes fulfills a value object, but other times rejects an error object.
    Invoke the function. Handle success by console logging "The data: " followed by the `data` property of the resolved value. Handle rejection by logging "The rejection: " followed by the `message` property of the rejected error.
    */
    function fetchData() {
      // Do not worry about how this function works internally
      return Math.floor(Math.random() * 2)
        ? Promise.resolve({ data: 'Promises rock!' })
        : Promise.reject(new Error('Server error, could not fetch data'))
    }
    fetchData().then(value=>{
      console.log(`The data: ${value.data}`);
    })
    .catch(err=>{
      console.log(`The rejection: ${err.message}`);
    })

    /*
    PROBLEM 3:
    The function queryDatabase below returns a promise that always rejects an error object.
    Invoke the function and handle failure by saving the error message into a variable, turning it to ALL CAPS, and writing it to the DOM as text content for the p#error element found in the HTML above.
   */
    function queryDatabase() {
      // Do not worry about how this function works internally
      return Promise.reject(new Error('Cannot connect to the database'))
    }
    // ENTER YOUR CODE HERE
    queryDatabase().catch(error =>{
      const message = error.message;
      const allCaps= message.toUpperCase();
      document.querySelector("#error").textContent = allCaps
    })

  </script>
</body>

</html>
